spring.application.name=user-service
server.port=9001

# Consumer Configuration
spring.kafka.consumer.bootstrap-servers=localhost:9092
# Used to identify Consumer Group
spring.kafka.consumer.group-id=user-group-1
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.StringSerializer